rules:
  - id: dockerfile.security.no-sudo-in-dockerfile.no-sudo-in-dockerfile
    patterns:
      - pattern: |
          RUN sudo ...
    message: >-
      Avoid using sudo in Dockerfiles. Running processes as a non-root user can
      help  reduce the potential impact of configuration errors and security
      vulnerabilities.
    metadata:
      category: security
      technology:
        - dockerfile
      cwe:
        - 'CWE-250: Execution with Unnecessary Privileges'
      owasp:
        - A05:2021 - Security Misconfiguration
        - A02:2025 - Security Misconfiguration
      references:
        - https://cwe.mitre.org/data/definitions/250.html
        - >-
          https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
      subcategory:
        - audit
      likelihood: LOW
      impact: LOW
      confidence: HIGH
      license: >-
        Semgrep Rules License v1.0. For more details, visit
        semgrep.dev/legal/rules-license
      vulnerability_class:
        - Improper Authorization
      source: >-
        https://semgrep.dev/r/dockerfile.security.no-sudo-in-dockerfile.no-sudo-in-dockerfile
      shortlink: https://sg.run/80Q7
      semgrep.dev:
        rule:
          r_id: 66384
          rv_id: 1262661
          rule_id: kxUlx1
          version_id: pZT03zY
          url: >-
            https://semgrep.dev/playground/r/pZT03zY/dockerfile.security.no-sudo-in-dockerfile.no-sudo-in-dockerfile
          origin: community
    languages:
      - dockerfile
    severity: WARNING
