rules:
  - id: dockerfile.security.missing-user-entrypoint.missing-user-entrypoint
    patterns:
      - pattern: |
          ENTRYPOINT $...VARS
      - pattern-not-inside: |
          USER $USER
          ...
    fix: |
      USER non-root
      ENTRYPOINT $...VARS
    message: >-
      By not specifying a USER, a program in the container may run as 'root'.
      This is a security hazard. If an attacker can control a process running as
      root, they may have control over the container. Ensure that the last USER
      in a Dockerfile is a USER other than 'root'.
    severity: ERROR
    languages:
      - dockerfile
    metadata:
      cwe:
        - 'CWE-269: Improper Privilege Management'
      category: security
      technology:
        - dockerfile
      confidence: MEDIUM
      owasp:
        - A04:2021 - Insecure Design
        - A06:2025 - Insecure Design
      references:
        - https://owasp.org/Top10/A04_2021-Insecure_Design
      subcategory:
        - audit
      likelihood: LOW
      impact: MEDIUM
      license: >-
        Semgrep Rules License v1.0. For more details, visit
        semgrep.dev/legal/rules-license
      vulnerability_class:
        - Improper Authorization
      source: >-
        https://semgrep.dev/r/dockerfile.security.missing-user-entrypoint.missing-user-entrypoint
      shortlink: https://sg.run/k281
      semgrep.dev:
        rule:
          r_id: 47272
          rv_id: 1262659
          rule_id: ReUW9E
          version_id: o5TbD21
          url: >-
            https://semgrep.dev/playground/r/o5TbD21/dockerfile.security.missing-user-entrypoint.missing-user-entrypoint
          origin: community
