rules:
  - id: dockerfile.security.dockerd-socket-mount.dockerfile-dockerd-socket-mount
    message: >-
      The Dockerfile(image) mounts docker.sock to the container which may allow
      an attacker already inside of the container to escape container and
      execute arbitrary commands on the host machine.
    languages:
      - dockerfile
      - yaml
    severity: ERROR
    metadata:
      cwe:
        - 'CWE-862: Missing Authorization'
        - 'CWE-269: Improper Privilege Management'
      confidence: HIGH
      likelihood: MEDIUM
      impact: HIGH
      subcategory:
        - audit
      technology:
        - dockerfile
      category: security
      references:
        - >-
          https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
        - https://redfoxsec.com/blog/insecure-volume-mounts-in-docker/
        - >-
          https://blog.quarkslab.com/why-is-exposing-the-docker-socket-a-really-bad-idea.html
      license: >-
        Semgrep Rules License v1.0. For more details, visit
        semgrep.dev/legal/rules-license
      vulnerability_class:
        - Improper Authorization
      source: >-
        https://semgrep.dev/r/dockerfile.security.dockerd-socket-mount.dockerfile-dockerd-socket-mount
      shortlink: https://sg.run/10AAQ
      semgrep.dev:
        rule:
          r_id: 146566
          rv_id: 945266
          rule_id: oqUgAAk
          version_id: WrTEoEq
          url: >-
            https://semgrep.dev/playground/r/WrTEoEq/dockerfile.security.dockerd-socket-mount.dockerfile-dockerd-socket-mount
          origin: community
    pattern-either:
      - patterns:
          - pattern: VOLUME $X
          - metavariable-regex:
              metavariable: $X
              regex: /var/run/docker.sock
      - patterns:
          - pattern-regex: '- "/var/run/docker.sock:.*"'
          - pattern-inside: |
              volumes:
                ...
