rules:
  - id: >-
      python.flask.security.audit.hardcoded-config.avoid_hardcoded_config_SECRET_KEY
    message: >-
      Hardcoded variable `SECRET_KEY` detected. Use environment variables or
      config files instead
    severity: ERROR
    metadata:
      likelihood: LOW
      impact: LOW
      confidence: LOW
      category: security
      cwe:
        - 'CWE-489: Active Debug Code'
      owasp:
        - A05:2021 - Security Misconfiguration
        - A02:2025 - Security Misconfiguration
      references:
        - https://bento.dev/checks/flask/avoid-hardcoded-config/
        - >-
          https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#builtin-configuration-values
        - >-
          https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#environment-and-debug-features
      subcategory:
        - audit
      technology:
        - flask
      license: >-
        Semgrep Rules License v1.0. For more details, visit
        semgrep.dev/legal/rules-license
      vulnerability_class:
        - Active Debug Code
      source: >-
        https://semgrep.dev/r/python.flask.security.audit.hardcoded-config.avoid_hardcoded_config_SECRET_KEY
      shortlink: https://sg.run/Ekde
      semgrep.dev:
        rule:
          r_id: 9537
          rv_id: 1263420
          rule_id: 4bUkX0
          version_id: l4TJRA9
          url: >-
            https://semgrep.dev/playground/r/l4TJRA9/python.flask.security.audit.hardcoded-config.avoid_hardcoded_config_SECRET_KEY
          origin: community
    languages:
      - python
    pattern-either:
      - pattern: $M.update(SECRET_KEY="=~/.*/")
      - pattern: $M.config['SECRET_KEY'] = "=~/.*/"
